'use client';

import { motion } from 'framer-motion';
import { ArrowUp, Camera, ChevronDown, Clock3, Dog, Heart, House, Leaf, Mail, MapPin, MessageCircleHeart, PawPrint } from 'lucide-react';
import { BookingForm } from '../components/BookingForm';
import { Navbar } from '../components/Navbar';
import { SectionTitle } from '../components/SectionTitle';

const fade = { initial: { opacity: 0, y: 22 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.2 }, transition: { duration: 0.55 } };
const reasons = [
  ['Personalized care', Heart, 'Each visit is shaped around your pet’s own routine, quirks, and comforts.'],
  ['Photo & video updates', Camera, 'A little window into their day, so you can relax while you’re away.'],
  ['Home is their happy place', House, 'Familiar spaces, familiar smells, and care right where they feel safest.'],
  ['Compassionate service', Heart, 'Gentle, patient attention for every personality and every stage of life.'],
  ['Reliable communication', MessageCircleHeart, 'Clear updates and a thoughtful check-in whenever you need one.'],
  ['Dogs & cats welcome', Dog, 'From energetic pups to quiet cats, all furry family members are welcome.'],
] as const;
const services = ['30 Minute Dog Walk', '60 Minute Dog Walk', '30 Minute Drop-In Visit', '60 Minute Drop-In Visit', 'Cat Drop-In Visit', 'Overnight House Sitting'];
const faqs = [
  ['How do I book?', 'Send a booking request below. I’ll reply to learn about your pets and arrange a complimentary meet & greet.'],
  ['Do you offer overnight stays?', 'Yes. Overnight house sitting is available so your pets have a familiar, caring presence through the night.'],
  ['Can medications be administered?', 'We can discuss medication routines during our meet & greet to make sure I can support your pet safely and confidently.'],
  ['Do you provide photo updates?', 'Always. You’ll receive photos, videos, and a note after visits so you know exactly how things are going.'],
  ['What payment methods do you accept?', 'Payment details will be shared with your booking confirmation. A deposit is required to reserve care dates.'],
  ['What areas do you serve?', 'Jade & Paws proudly serves Frederick, Maryland. Ask about your neighborhood when you reach out.'],
  ['Can I schedule a meet & greet?', 'Absolutely. A meet & greet helps us get acquainted and gives your pets a chance to say hello first.'],
] as const;

export default function Home() {
  return <main className="overflow-hidden"><Navbar />
    <section id="home" className="relative isolate bg-cream pb-16 pt-12 sm:pb-24 lg:pt-20"><div className="absolute -right-28 top-20 -z-10 size-80 rounded-full bg-sage/25 blur-3xl" /><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-2 lg:px-8"><motion.div {...fade}><p className="mb-5 flex items-center gap-2 text-sm font-semibold uppercase tracking-[.16em] text-olive"><PawPrint size={16} />Frederick, Maryland</p><h1 className="font-display text-5xl leading-[1.06] text-brown sm:text-6xl lg:text-7xl">Reliable, compassionate <i>pet care</i> close to home.</h1><p className="mt-6 max-w-xl text-[17px] leading-8 text-brown/75">Whether you’re away for the weekend or just need an extra helping hand, Jade & Paws provides personalized in-home care so your furry family members stay safe, comfortable, and loved.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#book-now" className="rounded-full bg-brown px-6 py-3.5 font-semibold text-cream shadow-soft transition hover:bg-olive">Book a Meet & Greet</a><a href="#services" className="rounded-full border border-brown/20 px-6 py-3.5 font-semibold text-brown transition hover:bg-beige">View Services</a></div></motion.div><motion.div {...fade} transition={{ duration: 0.7, delay: 0.15 }} className="relative"><div className="grid min-h-[440px] place-items-center overflow-hidden rounded-[2.5rem] bg-beige p-12 shadow-soft sm:min-h-[540px]"><div className="relative grid size-64 place-items-center rounded-full border-[18px] border-cream/60 bg-sage/30 sm:size-80"><PawPrint className="size-24 text-brown" strokeWidth={1.25} /><Leaf className="absolute -right-7 -top-7 size-24 rotate-45 text-olive/70" /><Leaf className="absolute -bottom-9 -left-9 size-24 -rotate-[135deg] text-olive/50" /></div></div><div className="absolute -bottom-5 -left-3 rounded-2xl bg-cream px-5 py-4 shadow-soft"><p className="font-display text-xl text-brown">Made for pets.</p><p className="text-sm text-brown/65">Loved like family.</p></div></motion.div></div></section>
    <section id="about" className="bg-white py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 lg:grid-cols-2 lg:px-8"><motion.div {...fade} className="order-2 grid min-h-[360px] place-items-center rounded-[2.5rem] bg-beige p-10 lg:order-1"><div className="text-center"><Heart className="mx-auto size-16 text-olive" strokeWidth={1.25} /><p className="mt-5 font-display text-3xl text-brown">A calm, caring presence</p><p className="mx-auto mt-3 max-w-xs text-sm leading-6 text-brown/70">Thoughtful care that keeps your pet’s day familiar, comfortable, and full of affection.</p></div></motion.div><motion.div {...fade}><p className="text-sm font-semibold uppercase tracking-[.16em] text-olive">A note from Jade</p><h2 className="mt-3 font-display text-4xl leading-tight text-brown sm:text-5xl">The kind of care I’d want for my own pets.</h2><p className="mt-6 leading-8 text-brown/75">Jade & Paws began with a simple belief: pets are happiest when their day still feels familiar. I bring calm, attentive care right to your home, whether that means a walk around the neighborhood, dinner and cuddles, or keeping them company overnight.</p><p className="mt-4 leading-8 text-brown/75">I take time to learn the little things — favorite toys, feeding routines, nervous habits, and the best scratching spot. You’ll always know how things are going, and your pets will have a friendly face they can count on.</p></motion.div></div></section>
    <section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Why families choose us" title="A softer, more personal kind of pet care." /><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{reasons.map(([title, Icon, copy]) => <motion.article whileHover={{ y: -6 }} key={title} className="rounded-3xl bg-white p-7 shadow-soft"><span className="grid size-11 place-items-center rounded-2xl bg-sage/30 text-brown"><Icon size={21} /></span><h3 className="mt-5 font-display text-2xl text-brown">{title}</h3><p className="mt-2 text-sm leading-6 text-brown/70">{copy}</p></motion.article>)}</div></div></section>
    <section id="services" className="bg-white py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Services" title="Care that fits your day — and theirs." copy="Every pet is different. We’ll choose a routine that feels easy, familiar, and right for your household." /><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <motion.article whileHover={{ y: -5 }} key={service} className="rounded-3xl border border-beige bg-cream/50 p-7"><Clock3 className="text-olive" /><h3 className="mt-7 font-display text-2xl text-brown">{service}</h3><p className="mt-2 text-sm leading-6 text-brown/70">{index === 5 ? 'Thoughtful care and comforting company while you’re away.' : 'A gentle, dependable visit tailored to your pet’s routine.'}</p><a href="#book-now" className="mt-5 inline-block text-sm font-semibold text-brown underline underline-offset-4">Ask about this service</a></motion.article>)}</div><div className="mt-8 grid gap-4 rounded-3xl bg-beige p-6 text-sm text-brown/80 sm:grid-cols-3"><p><b>Holiday care</b><br />Seasonal rates may apply.</p><p><b>Additional pets</b><br />Please tell me about every pet.</p><p><b>Meet & greet</b><br />Let’s meet before care begins.</p></div></div></section>
    <section id="book-now" className="bg-beige py-24"><div className="mx-auto max-w-4xl px-5"><SectionTitle eyebrow="Book a meet & greet" title="Tell me a little about your pets." copy="This is a request, not an automatic booking. I’ll personally follow up to confirm availability and make a plan together." /><BookingForm /></div></section>
    <section id="faq" className="bg-white py-24"><div className="mx-auto max-w-3xl px-5"><SectionTitle eyebrow="FAQ" title="A few helpful answers." />{faqs.map(([question, answer]) => <details key={question} className="group border-b border-beige py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-display text-xl text-brown">{question}<ChevronDown className="shrink-0 transition group-open:rotate-180" /></summary><p className="max-w-2xl pt-3 leading-7 text-brown/70">{answer}</p></details>)}</div></section>
    <section id="contact" className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-olive">Get in touch</p><h2 className="mt-3 font-display text-5xl text-brown">Let’s make your time away feel easier.</h2><div className="mt-8 space-y-5 text-brown/75"><p className="flex gap-3"><MapPin className="shrink-0 text-olive" />Serving Frederick, Maryland</p><a className="flex gap-3 hover:text-brown" href="mailto:jadeandpaws@gmail.com"><Mail className="shrink-0 text-olive" />jadeandpaws@gmail.com</a><p><b className="text-brown">Business hours</b><br />Monday–Sunday · By appointment</p></div></div><div className="grid min-h-80 place-items-center rounded-[2rem] bg-sage/35 p-8 text-center"><div><MapPin className="mx-auto size-10 text-brown" /><p className="mt-3 font-display text-2xl text-brown">Frederick, Maryland</p><a className="mt-4 inline-block text-sm font-semibold text-brown underline underline-offset-4" href="https://www.google.com/maps/search/?api=1&query=Frederick%2C%20Maryland" target="_blank" rel="noreferrer">View service area map</a></div></div></div></section>
    <footer className="bg-brown py-10 text-cream/75"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-5 px-5 text-center sm:flex-row sm:text-left lg:px-8"><p className="font-display text-2xl text-cream">Jade & Paws</p><p className="text-sm">© {new Date().getFullYear()} Jade & Paws. Made with care in Frederick, MD.</p><a href="#home" className="rounded-full border border-cream/25 p-2" aria-label="Back to top"><ArrowUp size={17} /></a></div></footer>
  </main>;
}
